#pragma once

#include "afxdialogex.h"
#include "afxbutton.h"
#include "resource.h"

/**
 * @class CCreateAccountDlg
 * @brief Modal dialog for creating a new bank account.
 *
 * Lets the user type the owner's name while previewing the account number
 * the engine will assign (read-only, generated by Account::peekNextAccountNumber()).
 * On confirmation, validates the name and exposes it via GetOwnerName() for
 * the caller to pass into BankManager::CreateAccount().
 */
class CCreateAccountDlg : public CDialogEx
{
	DECLARE_DYNAMIC(CCreateAccountDlg)

public:
	/**
	 * @brief Constructs the dialog.
	 * @param pParent Owner window, or nullptr for the application's main window.
	 */
	CCreateAccountDlg(CWnd* pParent = nullptr);   // standard constructor
	virtual ~CCreateAccountDlg();

// Dialog Data
#ifdef AFX_DESIGN_TIME
	enum { IDD = IDD_DIALOG_CREATE_ACCOUNT };
#endif

public:
	CEdit m_ctrlAccountNumber;
	CEdit m_ctrlOwnerName;

	// Bound via DDX_Control (required for SetFaceColor to take effect).
	CMFCButton m_btnCriar;
	CMFCButton m_btnCancelar;

	// Native C++ string used to carry the name read from the UI back to the business logic.
	CString m_strOwnerName;

	/**
	 * @brief Returns the validated owner name entered by the user.
	 * @return The trimmed owner name, only meaningful after the dialog closes with IDOK.
	 */
	CString GetOwnerName() const;

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	/**
	 * @brief Initializes fonts, button styling, and previews the next account number.
	 * @return TRUE to let the framework set the input focus.
	 */
	virtual BOOL OnInitDialog();

	/**
	 * @brief Validates the owner name and closes the dialog with IDOK on success.
	 *
	 * Rejects empty names, names containing digits, and names containing '|'
	 * (the field separator used in cadflow_data.txt).
	 */
	virtual void OnOK();

	// Brush and fonts for the white/blue visual style.
	CBrush  m_brBranco;     // Dialog's white background.
	CBrush  m_brushCinza;   // Grey background for the readonly field (account number).
	CFont   m_fontTitulo;   // Large font for the title.
	CFont   m_fontBotao;    // Bold font for button text.
	CFont   m_fontLabels;   // Larger font for labels and inputs.
	CStatic m_txtTitulo;    // Title static control, bound via DDX.

	/**
	 * @brief Paints the readonly account-number field grey and the title blue.
	 */
	afx_msg HBRUSH OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor);

	DECLARE_MESSAGE_MAP()
public:
	/**
	 * @brief Routes the "Confirm" button click to OnOK() for validated closing.
	 */
	afx_msg void OnBnClickedBtnConfirmCreate();
};
