#include "pch.h"
#include "CadflowBankSystem.h"
#include "CreateAccountDlg.h"
#include "Account.h"
#include "afxbutton.h"

IMPLEMENT_DYNAMIC(CCreateAccountDlg, CDialogEx)

CCreateAccountDlg::CCreateAccountDlg(CWnd* pParent /*=nullptr*/)
	: CDialogEx(IDD_DIALOG_CREATE_ACCOUNT, pParent)
{
}

CCreateAccountDlg::~CCreateAccountDlg()
{
}

void CCreateAccountDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
	
	DDX_Control(pDX, IDC_EDIT_ACCOUNT_NUMBER,  m_ctrlAccountNumber);
	DDX_Control(pDX, IDC_EDIT_OWNER_NAME,      m_ctrlOwnerName);
	// Buttons - without DDX_Control, SetFaceColor is ignored by Windows theming.
	DDX_Control(pDX, IDC_BTN_CONFIRM_CREATE,   m_btnCriar);
	DDX_Control(pDX, IDCANCEL,                 m_btnCancelar);
	// Title static control - bound so SetFont can be applied via the C++ member.
	DDX_Control(pDX, IDC_TXT_CRIAR_NOVA_CONTA, m_txtTitulo);
}

BEGIN_MESSAGE_MAP(CCreateAccountDlg, CDialogEx)
	ON_BN_CLICKED(IDC_BTN_CONFIRM_CREATE, &CCreateAccountDlg::OnBnClickedBtnConfirmCreate)
	ON_WM_CTLCOLOR()
END_MESSAGE_MAP()

// CCreateAccountDlg message handlers

BOOL CCreateAccountDlg::OnInitDialog()
{
	CDialogEx::OnInitDialog();

	SetWindowText(L"Sistema Bancario - Criar Nova Conta");

	m_brBranco.CreateSolidBrush(RGB(255, 255, 255));
	m_brushCinza.CreateSolidBrush(RGB(240, 240, 240));

	// -28 logical units renders at roughly 21pt on screen.
	m_fontTitulo.CreateFont(
		-28, 0, 0, 0, FW_BOLD, FALSE, FALSE, FALSE,
		DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
		CLEARTYPE_QUALITY, DEFAULT_PITCH | FF_SWISS, L"Segoe UI"
	);
	m_txtTitulo.SetFont(&m_fontTitulo);

	// -20 logical units renders at roughly 15pt on screen.
	m_fontBotao.CreateFont(
		-20, 0, 0, 0, FW_BOLD, FALSE, FALSE, FALSE,
		DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
		CLEARTYPE_QUALITY, DEFAULT_PITCH | FF_SWISS, L"Segoe UI"
	);

	// -19 logical units renders at roughly 14pt on screen.
	m_fontLabels.CreateFont(
		-19, 0, 0, 0, FW_NORMAL, FALSE, FALSE, FALSE,
		DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
		CLEARTYPE_QUALITY, DEFAULT_PITCH | FF_SWISS, L"Segoe UI"
	);
	GetDlgItem(IDC_TXT_LBL_NUM)->SetFont(&m_fontLabels);
	GetDlgItem(IDC_TXT_LBL_NAME)->SetFont(&m_fontLabels);
	GetDlgItem(IDC_EDIT_ACCOUNT_NUMBER)->SetFont(&m_fontLabels);
	GetDlgItem(IDC_EDIT_OWNER_NAME)->SetFont(&m_fontLabels);

	// Windows' visual theming otherwise overrides SetFaceColor on CMFCButton,
	// silently ignoring the custom blue/white styling below.
	CMFCButton::EnableWindowsTheming(FALSE);

	const COLORREF corAzul   = RGB(0, 80, 200);
	const COLORREF corBranco = RGB(255, 255, 255);
	const COLORREF corPreto  = RGB(0, 0, 0);

	m_btnCriar.SetFaceColor(corAzul, TRUE);
	m_btnCriar.SetTextColor(corBranco);
	m_btnCriar.SetImage(IDB_BITMAP8);
	m_btnCriar.SetFont(&m_fontBotao);

	m_btnCancelar.SetFaceColor(corBranco, TRUE);
	m_btnCancelar.SetTextColor(corPreto);
	m_btnCancelar.SetImage(IDB_BITMAP9);
	m_btnCancelar.SetFont(&m_fontBotao);

	// Account number field is locked - it is generated by the engine (see
	// Account::nextAccountNumber), never typed manually by the user.
	m_ctrlAccountNumber.SetReadOnly(TRUE);

	// Shows the number the *next* created account will receive - purely a
	// preview, since the real number is only assigned when CreateAccount() runs.
	CString strNextAccount;
	strNextAccount.Format(_T("%d"), Account::peekNextAccountNumber());
	m_ctrlAccountNumber.SetWindowText(strNextAccount);

	return TRUE;
}

void CCreateAccountDlg::OnBnClickedBtnConfirmCreate()
{
	// Routes the click through the same validated close path used for Enter/OnOK, instead of duplicating logic here.
	OnOK();
}

void CCreateAccountDlg::OnOK()
{
	// Read directly from the CEdit rather than relying on DDX_Text, since the
	// name only needs to be pulled once, at validation time.
	m_ctrlOwnerName.GetWindowText(m_strOwnerName);

	// Trim before the empty-check below, otherwise a name made only of spaces would pass as "non-empty".
	m_strOwnerName.Trim();

	if (m_strOwnerName.IsEmpty()) {
		AfxMessageBox(L"O Nome do Titular nao pode estar vazio.", MB_ICONERROR | MB_OK);
		return;
	}

	// Digits are rejected here rather than in Account/BankManager, since this
	// is strictly a UI-input convention (owner names), not a business rule.
	for (int i = 0; i < m_strOwnerName.GetLength(); i++) {
		if (_istdigit(m_strOwnerName[i])) {
			AfxMessageBox(L"O Nome do Titular nao pode conter numeros.", MB_ICONERROR | MB_OK);
			return;
		}
	}

	// '|' is the field separator used in cadflow_data.txt (see BankManager::SaveToFile/LoadFromFile).
	// Allowing it in the name would corrupt parsing the next time the file is loaded.
	if (m_strOwnerName.Find(L'|') != -1) {
		AfxMessageBox(L"O Nome do Titular nao pode conter o caractere '|'.", MB_ICONERROR | MB_OK);
		return;
	}

	CDialogEx::OnOK();
}

CString CCreateAccountDlg::GetOwnerName() const
{
	return m_strOwnerName;
}

// Repaints static text/background per-control, since MFC's default dialog
// theme cannot express "readonly field grey, title blue, rest black" without this hook.
HBRUSH CCreateAccountDlg::OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor)
{
	HBRUSH hbr = CDialogEx::OnCtlColor(pDC, pWnd, nCtlColor);

	// Grey background signals to the user that the account-number field is locked/non-editable.
	if (nCtlColor == CTLCOLOR_EDIT && pWnd &&
		pWnd->GetDlgCtrlID() == IDC_EDIT_ACCOUNT_NUMBER)
	{
		pDC->SetBkColor(RGB(240, 240, 240));
		pDC->SetTextColor(RGB(80, 80, 80));
		return (HBRUSH)m_brushCinza.GetSafeHandle();
	}

	if (nCtlColor == CTLCOLOR_DLG || nCtlColor == CTLCOLOR_STATIC)
	{
		pDC->SetBkColor(RGB(255, 255, 255));

		// Only the dialog title gets the corporate blue; every other label stays black.
		if (pWnd && pWnd->GetDlgCtrlID() == IDC_TXT_CRIAR_NOVA_CONTA)
			pDC->SetTextColor(RGB(0, 80, 200));
		else
			pDC->SetTextColor(RGB(0, 0, 0));

		return (HBRUSH)m_brBranco.GetSafeHandle();
	}

	return hbr;
}
